// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BakeryEcomm.Models;

public partial class Bakery_Item
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(4, 2)")]
    public decimal Price { get; set; }

    public bool Drink { get; set; }

    [InverseProperty("Item")]
    public virtual ICollection<Order_Line> Order_Lines { get; set; } = new List<Order_Line>();
}