// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BakeryEcomm.Models;

[Table("Card_Info")]
public partial class Card_Info
{
    [Key]
    public int Id { get; set; }

    public int Card_Number { get; set; }

    public int CVC { get; set; }

    public DateOnly Exp_Date { get; set; }

    [Required]
    [StringLength(50)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string Cardholder_Name { get; set; }

    public int Customer_Id { get; set; }

    [ForeignKey("Customer_Id")]
    [InverseProperty("Card_Infos")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Card")]
    public virtual ICollection<Order_Header> Order_Headers { get; set; } = new List<Order_Header>();
}