// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BakeryEcomm.Models;

[Table("Customer")]
public partial class Customer
{
    [Key]
    public int Id { get; set; }

    [StringLength(20)]
    public string First_Name { get; set; }

    [StringLength(20)]
    public string Last_Name { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Card_Info> Card_Infos { get; set; } = new List<Card_Info>();

    [InverseProperty("Customer")]
    public virtual ICollection<Order_Header> Order_Headers { get; set; } = new List<Order_Header>();
}