// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BakeryEcomm.Models;

public partial class Drink_Addon
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(10)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(3, 2)")]
    public decimal Upcharge { get; set; }

    [InverseProperty("ItemNavigation")]
    public virtual ICollection<Order_Line> Order_Lines { get; set; } = new List<Order_Line>();
}