// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BakeryEcomm.Models;

[Table("Order_Line")]
public partial class Order_Line
{
    [Key]
    public int Id { get; set; }

    public int Order_Header_Id { get; set; }

    public int Item_Id { get; set; }

    public bool Addon { get; set; }

    [ForeignKey("Item_Id")]
    [InverseProperty("Order_Lines")]
    public virtual Bakery_Item Item { get; set; }

    [ForeignKey("Item_Id")]
    [InverseProperty("Order_Lines")]
    public virtual Drink_Addon ItemNavigation { get; set; }

    [ForeignKey("Order_Header_Id")]
    [InverseProperty("Order_Lines")]
    public virtual Order_Header Order_Header { get; set; }
}