// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BakeryEcomm.Models;

[Table("Order_Header")]
public partial class Order_Header
{
    [Key]
    public int Id { get; set; }

    public int Customer_Id { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal Total_Price { get; set; }

    public int Card_Id { get; set; }

    [Required]
    public byte[] Timestamp { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Ready_By { get; set; }

    [ForeignKey("Card_Id")]
    [InverseProperty("Order_Headers")]
    public virtual Card_Info Card { get; set; }

    [ForeignKey("Customer_Id")]
    [InverseProperty("Order_Headers")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Order_Header")]
    public virtual ICollection<Order_Line> Order_Lines { get; set; } = new List<Order_Line>();
}